import React, { useState } from 'react';
import { Sparkles, RefreshCw, X, ChevronRight, BarChart3, ShieldCheck, AlertCircle } from 'lucide-react';
import { useAiNetworkSummary, useAiStatus } from '@/hooks';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import clsx from 'clsx';

/**
 * AI Network Summary Component
 * Displays a 24-hour health summary generated by Gemini
 */
export default function AiNetworkSummary() {
    const [isOpen, setIsOpen] = useState(false);
    const { isEnabled, hasKey } = useAiStatus();
    const { data, isLoading, isError, refetch, isRefetching } = useAiNetworkSummary({
        enabled: isOpen && isEnabled
    });

    const summary = data?.summary;

    return (
        <div className="mb-6">
            {!isOpen ? (
                <button
                    onClick={() => setIsOpen(true)}
                    className="w-full p-4 rounded-xl glass-panel border border-primary/20 bg-gradient-to-r from-primary/10 to-transparent hover:from-primary/20 transition-all flex items-center justify-between group"
                >
                    <div className="flex items-center gap-3">
                        <div className="bg-primary/20 p-2 rounded-lg group-hover:scale-110 transition-transform">
                            <Sparkles className="w-5 h-5 text-primary" />
                        </div>
                        <div className="text-left">
                            <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
                                Daily AI Summary
                                <span className="bg-emerald-500/20 text-emerald-400 text-[10px] px-1.5 py-0.5 rounded border border-emerald-500/20">NEW</span>
                            </h3>
                            <p className="text-xs text-slate-400">Get a Gemini-powered overview of the last 24 hours.</p>
                        </div>
                    </div>
                    <ChevronRight className="w-5 h-5 text-slate-500 group-hover:translate-x-1 transition-transform" />
                </button>
            ) : (
                <div className="rounded-xl glass-panel border border-primary/30 overflow-hidden bg-slate-900/40 backdrop-blur-md animate-in fade-in slide-in-from-top-2 duration-300">
                    <div className="p-4 border-b border-slate-700/50 flex items-center justify-between bg-primary/5">
                        <div className="flex items-center gap-2">
                            <Sparkles className="w-4 h-4 text-primary animate-pulse" />
                            <h3 className="text-sm font-bold text-white uppercase tracking-tight">24h Network Intelligence</h3>
                        </div>
                        <div className="flex items-center gap-1">
                            <button
                                onClick={() => refetch()}
                                disabled={isLoading || isRefetching}
                                className="p-1.5 text-slate-400 hover:text-white transition-colors disabled:opacity-50"
                            >
                                <RefreshCw className={clsx("w-3.5 h-3.5", (isLoading || isRefetching) && "animate-spin")} />
                            </button>
                            <button
                                onClick={() => setIsOpen(false)}
                                className="p-1.5 text-slate-400 hover:text-white transition-colors"
                            >
                                <X className="w-4 h-4" />
                            </button>
                        </div>
                    </div>

                    <div className="p-5">
                        {isLoading || isRefetching ? (
                            <div className="space-y-4 animate-pulse">
                                <div className="h-4 bg-slate-800 rounded w-3/4"></div>
                                <div className="h-4 bg-slate-800 rounded w-1/2"></div>
                                <div className="space-y-2 pt-2">
                                    <div className="h-3 bg-slate-800/50 rounded w-full"></div>
                                    <div className="h-3 bg-slate-800/50 rounded w-full"></div>
                                    <div className="h-3 bg-slate-800/50 rounded w-5/6"></div>
                                </div>
                                <div className="flex items-center gap-2 pt-2 text-xs text-primary/60 italic">
                                    <Sparkles className="w-3 h-3" />
                                    <span>Gemini 1.5 is synthesizing your network trends...</span>
                                </div>
                            </div>
                        ) : isError ? (
                            <div className="flex flex-col items-center justify-center py-6 text-center">
                                <AlertCircle className="w-8 h-8 text-red-500/50 mb-2" />
                                <p className="text-sm text-slate-400 mb-4">Could not generate AI summary at this time.</p>
                                <Button size="sm" variant="outline" onClick={() => refetch()}>Try Again</Button>
                            </div>
                        ) : !isEnabled ? (
                            <div className="flex flex-col items-center justify-center py-6 text-center">
                                <Sparkles className="w-8 h-8 text-primary/30 mb-2" />
                                <h4 className="text-white font-bold mb-1">AI Belum Aktif</h4>
                                <p className="text-xs text-slate-400 mb-4 max-w-[250px]">
                                    Aktifkan fitur AI Intelligence di menu Settings untuk melihat rangkuman harian.
                                </p>
                                <Link to="/settings">
                                    <Button size="sm">Buka Pengaturan</Button>
                                </Link>
                            </div>
                        ) : !hasKey ? (
                            <div className="flex flex-col items-center justify-center py-6 text-center">
                                <AlertCircle className="w-8 h-8 text-amber-500/50 mb-2" />
                                <h4 className="text-white font-bold mb-1">API Key Kosong</h4>
                                <p className="text-xs text-slate-400 mb-4 max-w-[250px]">
                                    Anda perlu memasukkan Gemini API Key pribadi Anda di pengaturan agar rangkuman dapat dibuat.
                                </p>
                                <Link to="/settings">
                                    <Button size="sm" variant="outline">Set Sekarang</Button>
                                </Link>
                            </div>
                        ) : (
                            <div className="fade-in duration-500">
                                <div className="text-sm leading-relaxed text-slate-200 whitespace-pre-wrap font-sans bg-slate-800/20 p-4 rounded-lg border border-slate-700/30">
                                    {summary}
                                </div>
                                <div className="mt-4 flex flex-wrap gap-4 text-[10px] text-slate-500 font-medium uppercase tracking-widest px-1">
                                    <div className="flex items-center gap-1.5">
                                        <BarChart3 className="w-3 h-3 text-emerald-500" />
                                        <span>Trend Analysis</span>
                                    </div>
                                    <div className="flex items-center gap-1.5">
                                        <ShieldCheck className="w-3 h-3 text-primary" />
                                        <span>Health Checked</span>
                                    </div>
                                    <div className="ml-auto text-primary/40"> Powered by Gemini 1.5 Flash </div>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
