// Export all schemas
export * from './users';
export * from './groups';
export * from './routers';
export * from './alerts';
export * from './settings';
export * from './user-routers';
export * from './notifications';
export * from './pppoe';
export * from './olts';
export * from './onus';
export * from './presets';
export * from './tenants';
export * from './user-tenants';
export * from './topology_schematics';
export * from './performance-history';
export * from './interface-metrics';
export * from './router_backups';
export * from './genieacs-backups';
