name: CI (Build and Lint)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: CI Check (Lint)
      run: npm run lint
      
    - name: CI Check (Build)
      run: npm run build

  docker-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Build API Image
      run: docker build -t mikrotik-monitor-api-test -f apps/api/Dockerfile .
      
    - name: Test Build Web Image
      run: docker build -t mikrotik-monitor-web-test -f apps/web/Dockerfile .
